### PR TITLE
Comment style

### LINKED ISSUE #50: Logger Comment Formatting
Change all logger comments to "new format" which looks more aesthetically pleasing. 

## Old Format

We should color code essentially the equivalent of HTTP 1xx 2xx 3xx 4xx 5xx class errors in these bot comments. 

```diff
# 1xx Class (Informational Responses)
```

```diff
+ 2xx Class (Successful Responses)
```

```diff
@@ 3xx Class (Redirection Messages) @@
```

```diff
! 4xx Class (Client Error Responses)
```

```diff
- 5xx Class (Server Error Responses)
```

## New Format

As it turns out, GitHub flavored markdown includes these handy color indicators. We can use the same color keys but instead of diff syntax, we use this syntax. 

This should be applied across all kernel and plugin messages.

It might even be handy to rename the methods in our logger if its still attached to posting comments. The inspiration behind the rename is so that the class of message is no longer subjective.

```typescript
logger.info();
logger.success();
logger.redirect();
logger.clientError();
logger.serverError();
```

### Status Codes

Based on HTTP status codes, we should color code the responses. The only problem is that some of the headers can be misleading, but it does look a lot more aesthetically pleasing than the diffs. The left border in particular I think is a great minimal representation of the status. 

> [!NOTE]
> 1xx

> [!TIP]
> 2xx

> [!IMPORTANT]
> 3xx

> [!WARNING]
> 4xx

> [!CAUTION]
> 5xx

### Source Code

```markdown
> [!NOTE]
> 1xx

> [!TIP]
> 2xx

> [!IMPORTANT]
> 3xx

> [!WARNING]
> 4xx

> [!CAUTION]
> 5xx
```

### About HTTP Status Code Classes

> HTTP status codes are standardized codes returned by web servers to indicate the result of a client's request. These codes are grouped into five classes, each signifying a different category of response:
>
> ---
> 
> ### **1xx: Informational**
> 
> **Description:** The 1xx class of status codes indicates that the server has received the request and is continuing the process. These are provisional responses, providing interim information while the server continues to process the request.
> 
> **Common Status Codes:**
> 
> - **100 Continue:** Indicates that the initial part of the request has been received and the client should continue with the rest of the request.
> - **101 Switching Protocols:** Informs the client that the server is switching to a different protocol as requested.
> - **102 Processing (WebDAV):** Signals that the server has received and is processing the request, but no response is available yet.
> 
> ---
> 
> ### **2xx: Success**
> 
> **Description:** The 2xx class signifies that the client's request was successfully received, understood, and accepted by the server.
> 
> **Common Status Codes:**
> 
> - **200 OK:** The request has succeeded. The meaning varies depending on the HTTP method used.
> - **201 Created:** The request has been fulfilled, resulting in the creation of a new resource.
> - **202 Accepted:** The request has been accepted for processing, but the processing is not complete.
> - **204 No Content:** The server successfully processed the request and is not returning any content.
> - **206 Partial Content:** The server is delivering only part of the resource due to a range header sent by the client.
> 
> ---
> 
> ### **3xx: Redirection**
> 
> **Description:** The 3xx class indicates that further action is needed to complete the request. This usually means a redirection to a different resource.
> 
> **Common Status Codes:**
> 
> - **301 Moved Permanently:** The resource has been permanently moved to a new URL.
> - **302 Found:** The resource resides temporarily under a different URL.
> - **303 See Other:** The response can be found under a different URI and should be retrieved using a GET method.
> - **304 Not Modified:** Indicates that the resource has not been modified since the last request.
> - **307 Temporary Redirect:** The request should be repeated with another URI; however, future requests should still use the original URI.
> 
> ---
> 
> ### **4xx: Client Error**
> 
> **Description:** The 4xx class signifies errors that appear to have been caused by the client. These codes indicate that the request contains bad syntax or cannot be fulfilled.
> 
> **Common Status Codes:**
> 
> - **400 Bad Request:** The server cannot process the request due to a client error (e.g., malformed request syntax).
> - **401 Unauthorized:** Authentication is required and has failed or has not yet been provided.
> - **403 Forbidden:** The client does not have access rights to the content.
> - **404 Not Found:** The server cannot find the requested resource.
> - **405 Method Not Allowed:** The request method is known by the server but is not supported by the target resource.
> - **408 Request Timeout:** The server timed out waiting for the request.
> - **409 Conflict:** The request could not be completed due to a conflict with the current state of the resource.
> - **410 Gone:** The resource requested is no longer available and will not be available again.
> - **429 Too Many Requests:** The user has sent too many requests in a given amount of time ("rate limiting").
> 
> ---
> 
> ### **5xx: Server Error**
> 
> **Description:** The 5xx class indicates that the server failed to fulfill a valid request. The server is aware that it has encountered an error or is otherwise incapable of performing the request.
> 
> **Common Status Codes:**
> 
> - **500 Internal Server Error:** A generic error message when the server encounters an unexpected condition.
> - **501 Not Implemented:** The server either does not recognize the request method or lacks the ability to fulfill it.
> - **502 Bad Gateway:** The server was acting as a gateway or proxy and received an invalid response from the upstream server.
> - **503 Service Unavailable:** The server is not ready to handle the request, often due to maintenance or overload.
> - **504 Gateway Timeout:** The server was acting as a gateway or proxy and did not receive a timely response from the upstream server.
> - **505 HTTP Version Not Supported:** The server does not support the HTTP protocol version used in the request.
> 
> ---
> 
> Understanding these status codes is essential for debugging web applications and ensuring efficient client-server communication. Each code provides specific information about what happened with a request, allowing developers to handle responses appropriately.

### PR DESCRIPTION
**Pull request by whilefoo**
Resolves #50

### CODE REVIEW

**Comment by whilefoo** [comment]
@0x4007 @gentlementlegen

**Review by 0x4007 — CHANGES_REQUESTED** [review]
Redundant entries should be replaced.

File: src/logs.ts [hunk 1]
```diff
@@ -131,40 +142,27 @@ export class Logs {
...
   }
 
-  private _diffColorCommentMessage(type: string, message: string) {
-    const diffPrefix = {
-      fatal: "-", // - text in red
-      ok: "+", // + text in green
-      error: "!", // ! text in orange
-      info: "#", // # text in gray
-      debug: "@@@@", // @@ text in purple (and bold)@@
+  private _diffColorCommentMessage(type: LogLevelWithOk, message: string) {
```
Comment (0x4007) [inline src/logs.ts:145]: It is also no longer called diff

**Review by 0x4007 — CHANGES_REQUESTED** [review]

**Comment by whilefoo** [comment]
> Redundant entries should be replaced.

We have more logger methods than possible formattings. I'd remove `verbose` because I think it's semantically the same as `debug`, but `fatal` is different than `error` because it displays the metadata instead of hiding it in the comment

**Comment by gentlementlegen** [comment]
Tested here: https://github.com/Meniole/ubiquity-os-kernel/issues/20

Works fine. Maybe it is strange to have `Important` for debug and might be better without any header, and use `Important` for verbose?

**Comment by 0x4007** [comment]
> Tested here: https://github.com/Meniole/ubiquity-os-kernel/issues/20
> 
> 
> 
> Works fine. Maybe it is strange to have `Important` for debug and might be better without any header, and use `Important` for verbose?

We can try your suggestions and iterate after. 

---

I still think that we should use client error and server error because that is not ambiguous and all plug-in developers are more likely to agree on the definitions and conform to the standard

**Comment by gentlementlegen** [comment]
What is server and what is client? Because the kernel, the Actions and the Workers can all post errors. I think this should be the responsibility of the developer to add these in the metadata and not in the message itself

**Comment by 0x4007** [comment]
https://github.com/ubiquity-os/ubiquity-os-logger/issues/50#issuecomment-2540343090

**Comment by gentlementlegen** [comment]
I think this should be in the metadata, it doesn't give any useful information to the user, and for the debug we now have the url inside of the metadata and can easily figure out what broke. A logger should be generic and able to log anything without depending on the platform or environment, which is why we could embed this info in the metadata (which becomes the SDK responsibility)

**Comment by 0x4007** [comment]
> A logger should be generic and able to log anything without depending on the platform or environment

Generally, I agree, but when I first implemented this, I was trying to solve a problem of logging in three separate places:

- the console, for local development
- GitHub comment, for triage
- The database, for later review

Due to these requirements this was designed specifically for this platform and environment (UbiquityOS plugins, interacting with GitHub)

**Comment by whilefoo** [comment]
> Works fine. Maybe it is strange to have `Important` for debug and might be better without any header, and use `Important` for verbose?

So `debug` would be in plain-text (raw)?

---

I still don't see the benefit in separating `error` into `clientError` and `serverError`, it's not useful either to the user or developer. Client errors only happen when using commands incorrectly and I think it's descriptive enough to use `logger.error("Provided address is in incorrect format")`

**Comment by gentlementlegen** [comment]
@whilefoo yes or contained within a code block? But that was just a suggestion I don't mind it the way it is, just that we maybe want debug to stand out because it is non-normal logs.

**Comment by whilefoo** [comment]
> @whilefoo yes or contained within a code block? But that was just a suggestion I don't mind it the way it is, just that we maybe want debug to stand out because it is non-normal logs.

Wouldn't making it without header make it stand out less :D 
It seems `verbose` is only used [text-conversation-rewards](https://github.com/search?q=org%3Aubiquity-os-marketplace%20logger.verbose&type=code) where it's logging a stringified JSON so maybe that's more suitable for a code block?

**Comment by gentlementlegen** [comment]
@whilefoo Fair enough haha. Yes across our plugins I don't think verbose is used much, maybe in `command-start-stop` as well? It is hard to tell when this should be chosen instead of `ok` or `info`. In my thoughts it was just because I wouldn't expect `debug` messages to actually get posted to an issue, thus not needing the header.

**Comment by whilefoo** [comment]
> In my thoughts it was just because I wouldn't expect `debug` messages to actually get posted to an issue, thus not needing the header.

That's true, `debug` and `verbose` usually aren't thrown

**Review by gentlementlegen — APPROVED** [review]
